In [24]:
import pandas as pd

In [25]:
df = pd.read_csv("ventas.csv")
df.head()

   producto;categoria;precio;cantidad;region
0  Laptop Lenovo;Tecnologia;2500;10;Arequipa
1       Mouse Logitech;Tecnologia;45;50;Lima
2   Silla Ergonomica;Muebles;350;15;Arequipa
3    Monitor Samsung;Tecnologia;800;20;Cusco
4              Escritorio;Muebles;450;8;Lima

In [28]:
df = pd.read_csv("ventas.csv", sep=";")
df.head()

           producto   categoria  precio  cantidad    region
0     Laptop Lenovo  Tecnologia    2500        10  Arequipa
1    Mouse Logitech  Tecnologia      45        50      Lima
2  Silla Ergonomica     Muebles     350        15  Arequipa
3   Monitor Samsung  Tecnologia     800        20     Cusco
4        Escritorio     Muebles     450         8      Lima

In [ ]:
df_prueba = pd.read_csv("ventas.csv", sep=";", nrows=3)
df_prueba.head()

           producto   categoria  precio  cantidad    region
0     Laptop Lenovo  Tecnologia    2500        10  Arequipa
1    Mouse Logitech  Tecnologia      45        50      Lima
2  Silla Ergonomica     Muebles     350        15  Arequipa