In [6]:
import pandas as pd
import openpyxl

In [7]:
df = pd.read_excel("reporte.xlsx")
df.head()

       mes  ingresos  gastos
0    Enero     15000    9000
1  Febrero     18500    9800
2    Marzo     21000   10200

In [8]:
df = pd.read_excel("reporte.xlsx", sheet_name="Ventas2023")
df.head()

       mes  ingresos  gastos
0    Enero     12000    8000
1  Febrero     13500    8300
2    Marzo     14800    8600

In [10]:
df_todas = pd.read_excel("reporte.xlsx", sheet_name=None)
print(df_todas.keys())

dict_keys(['Ventas2024', 'Ventas2023'])

In [11]:
df_todas["Ventas2024"]

       mes  ingresos  gastos
0    Enero     15000    9000
1  Febrero     18500    9800
2    Marzo     21000   10200